title = "Scoreboard modules"  # From Git
gitRepoUrl = "https://github.com/fxxizan/Timer-module" # From Git

gitSourceBranch = "master"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "https://images-ext-1.discordapp.net/external/Eoiq1BMsMwpW8qnkJiqMtvEhRsFaW-X-37aFsFSSQd0/%3Fsize%3D4096/https/cdn.discordapp.com/icons/1348266414066372620/5517ec0a3363f2ae54b0c0d71c163e16.png?format=webp&quality=lossless"

[footer]
style = "dark"
copyright = "Copyright © 2025 fxxizan & MPS Developer Hub."

[[navbar.items]]
href = "https://discord.gg/JfukYC8rCW"
label = "Discord"
position = "right"